#ifndef _GPIO_H
#define _GPIO_H

#include <avr/io.h>

#define GPIO_HIGH 0x1
#define GPIO_LOW  0x0

#define CONCAT(x,y) x ##  y

#define GPIO_SET_HIGH(PORTID, BITNUM) CONCAT(PORT, PORTID) |= (1 << BITNUM)
#define GPIO_SET_LOW(PORTID, BITNUM) CONCAT(PORT, PORTID) &= ~(1 << BITNUM)

#define GPIO_OUTPUT(PORTID, BITNUM) CONCAT(DDR, PORTID) |= (1 << BITNUM)
#define GPIO_INPUT(PORTID, BITNUM) CONCAT(DDR, PORTID) &= ~(1 << BITNUM)

#define GPIO_INPUT_PULLUP(PORTID, BITNUM) CONCAT(DDR, PORTID) &= ~(1 << BITNUM); CONCAT(PORT, PORTID) |= (1 << BITNUM)
#define GPIO_INPUT_PULLDOWN(PORTID, BITNUM) CONCAT(DDR, PORTID) &= ~(1 << BITNUM); CONCAT(PORT, PORTID) &= ~(1 << BITNUM)

#define GPIO_READ(PORTID, BITNUM) (CONCAT(PIN, PORTID) & (1 << BITNUM))?GPIO_HIGH:GPIO_LOW;


#endif
