/*  Copyright (c) 2015 B. Sidhipong <bsidhipong@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>. */

#include <avr/common.h>
#include <avr/io.h>
#include <avr/interrupt.h>

#include "tinyspi.h"
#include <gpio.h>
#include <util/delay.h>


/*! \brief  Data input register buffer.
 *
 *  Incoming bytes are stored in this byte until the next transfer is complete.
 *  This byte can be used the same way as the SPI data register in the native
 *  SPI module, which means that the byte must be read before the next transfer
 *  completes and overwrites the current value.
 */
uint8_t storedSPIData;

/*! \brief  Driver status bit structure.
 *
 *  This struct contains status flags for the driver.
 *  The flags have the same meaning as the corresponding status flags
 *  for the native SPI module. The flags should not be changed by the user.
 *  The driver takes care of updating the flags when required.
 */
struct SPIdriverStatus_t {
    uint8_t masterMode : 1;       //!< True if in master mode.
    uint8_t transferComplete : 1; //!< True when transfer completed.
};

volatile struct SPIdriverStatus_t spiX_status; //!< The driver status bits.

//-----------------------------------------------------------------------
// For MCU with SPI support
#if defined(SPCR)

// set PORT and PIN
#if defined(__AVR_ATmega8535__) || defined(__AVR_ATmega32__)
#define PORT_SPI    PORTB
#define PIN_SPI     PINB
#define DDR_SPI		DDRB
#define DD_MOSI		DDB5
#define DD_MISO		DDB6
#define DD_SCK		DDB7
#define DD_CS		DDB4
#elif defined(__AVR_ATmega328P__)
#define PORT_SPI    PORTB
#define PIN_SPI     PINB
#define DDR_SPI		DDRB
#define DD_MOSI		DDB3
#define DD_MISO		DDB4
#define DD_SCK		DDB5
#define DD_CS		DDB2
#endif

void SPIManager::startSlave() {
    DDR_SPI |= _BV(DD_MISO); // output
    DDR_SPI &= ~(_BV(DD_MOSI) | _BV(DD_SCK) | _BV(DD_CS)); // input

    SPCR = (0 << SPIE) | // no interrupt
           (1 << SPE)  | // enable SPI
           (0 << DORD) | // MSB first
           (0 << MSTR) | // set as slave
           (0 << CPOL) | (0 << CPHA) | // mode 0
           (0 << SPR1) | (0 << SPR0); // CPU freq / 4, no effect in slave mode, clock is generated by master

    // pull up on ChipSelect
    PORT_SPI |= _BV(DD_CS);

    this->_statusRegister = SPI_MODE_SLAVE;
    SPDR = this->_statusRegister;
}

void SPIManager::startMaster() {
    DDR_SPI &= ~(_BV(DD_MISO)); // input
    DDR_SPI |= (_BV(DD_MOSI) | _BV(DD_SCK) | _BV(DD_CS)); // output

    SPCR = (0 << SPIE) | // no interrupt
           (1 << SPE)  | // enable SPI
           (0 << DORD) | // MSB first
           (1 << MSTR) | // set as master
           (0 << CPOL) | (0 << CPHA) | // mode 0
           (1 << SPI2X) | (1 << SPR1) | (1 << SPR0); // CPU freq / 64

    // init output
    PORT_SPI &= ~(_BV(DD_MOSI) | _BV(DD_SCK) | _BV(DD_CS));

    this->_statusRegister = SPI_MODE_MASTER;
    SPDR = this->_statusRegister;
}

void SPIManager::begin(uint8_t cspin) {
    // pull low for chip select
    PORT_SPI &= ~_BV(cspin);
}

void SPIManager::end(uint8_t cspin) {
    PORT_SPI |= _BV(cspin);
}

bool SPIManager::receiveCommand(uint8_t& command) {
    if (this->isMaster()) return false; // not used if master

    bool success = true;
    // Wait for reception complete or CS HIGH
    do { } while (bit_is_clear(SPSR, SPIF) && bit_is_clear(PIN_SPI, DD_CS));


    // do this before reading SPDR, to not reset SPIF
    if (bit_is_set(PIN_SPI, DD_CS) && bit_is_clear(SPSR, SPIF)) {
        // loop is broken because CS is released (HIGH)
        success = false;
    }

    // copy Data Register
    command = SPDR;

    return success;
}

bool SPIManager::execCommand(uint8_t size, uint8_t* outbuffer,  uint8_t* inbuffer) {
    if (this->isMaster()) return false; // not used if master

    bool success = true;

    for(uint8_t i =0; i < size; i++) {
        // copy output byte
        SPDR = outbuffer[i];
        // Wait for reception complete or CS HIGH
        do { } while (bit_is_clear(SPSR, SPIF) && bit_is_clear(PIN_SPI, DD_CS));

        // do this before reading SPDR, to not reset SPIF
        if (bit_is_set(PIN_SPI, DD_CS) && bit_is_clear(SPSR, SPIF)) {
            // loop is broken because CS is released (HIGH)
            success = false;
            break;
        }

        // copy Data Register
        inbuffer[i] = SPDR;
    }
    
    SPDR = this->_statusRegister;
    return success;
}

bool SPIManager::sendCommand(uint8_t& command) {
    if (this->isSlave()) return false; // not used if slave

    SPDR = command;
    // Wait for send complete
    loop_until_bit_is_set(SPSR, SPIF);
    
    // copy Data Register
    command = SPDR;

    return true;
}

bool SPIManager::send(uint8_t data) {
    if (this->isSlave()) return false; // not used if slave

    SPDR = data;
    // Wait for send complete
    loop_until_bit_is_set(SPSR, SPIF);

    return true;
}

bool SPIManager::sendCommandData(uint8_t size, uint8_t* outbuffer,  uint8_t* inbuffer) {
    if (this->isSlave()) return false; // not used if slave

    for(uint8_t i =0; i < size; i++) {
        // copy output byte
        SPDR = outbuffer[i];
        // Wait for send complete
        loop_until_bit_is_set(SPSR, SPIF);
        // copy Data Register
        inbuffer[i] = SPDR;
    }
    
    return true;
}

bool SPIManager::sendCommandData(uint8_t size, uint8_t* inoutbuffer) {
    if (this->isSlave()) return false; // not used if slave

    for(uint8_t i =0; i < size; i++) {
        // copy output byte
        SPDR = inoutbuffer[i];
        // Wait for send complete
        loop_until_bit_is_set(SPSR, SPIF);
        // copy Data Register
        inoutbuffer[i] = SPDR;
    }
    
    return true;
}

#endif

//-----------------------------------------------------------------------
// For MCU without SPI, but support USI
// Based on appnote: AVR319 - Using the USI module for SPI communication.
#if defined(USISR)

/* USI port and pin definitions. */
#if defined(__AVR_ATtiny84__)
#define USI_OUT_REG	PORTA	//!< USI port output register.
#define USI_IN_REG	PINA	//!< USI port input register.
#define USI_DIR_REG	DDRA	//!< USI port direction register.
#define USI_CLOCK_PIN	PA4//!< USI clock I/O pin.
#define USI_DATAIN_PIN	PA6	//!< USI data input pin.
#define USI_DATAOUT_PIN	PA5	//!< USI data output pin.
#else
#define USI_OUT_REG	PORTB	//!< USI port output register.
#define USI_IN_REG	PINB	//!< USI port input register.
#define USI_DIR_REG	DDRB	//!< USI port direction register.
#define USI_CLOCK_PIN	PB2	//!< USI clock I/O pin.
#define USI_DATAIN_PIN	PB0	//!< USI data input pin.
#define USI_DATAOUT_PIN	PB1	//!< USI data output pin.
#endif

/*! \brief  Initialize USI as SPI master.
 *
 *  This function sets up all pin directions and module configurations.
 *  Use this function initially or when changing from slave to master mode.
 *  Note that the stored USIDR value is cleared.
 */
void spi_master_init()
{
    // Configure port directions.
    USI_DIR_REG |= (1<<USI_DATAOUT_PIN) | (1<<USI_CLOCK_PIN); // Outputs.
    USI_DIR_REG &= ~(1<<USI_DATAIN_PIN);                      // Inputs.

    // Configure USI to 3-wire master mode with overflow interrupt.
    USICR = (1<<USIWM0) | (0<<USIWM1) | // 3 wire mode
            (1<<USICS1) | (0<<USICS0); // software clock 
            
    // Init driver status register.
    spiX_status.masterMode       = 1;
}

/*! \brief  Initialize USI as SPI slave.
 *
 *  This function sets up all pin directions and module configurations.
 *  Use this function initially or when changing from master to slave mode.
 *  Note that the stored USIDR value is cleared.
 *
 *  \param spi_mode  Required SPI mode, must be 0 or 1.
 */
void spi_slave_init()
{
    // Configure port directions.
    USI_DIR_REG |= (1<<USI_DATAOUT_PIN) ; // Outputs.
    USI_DIR_REG &= ~(1<<USI_DATAIN_PIN) ; // Inputs.

    // Configure USI to 3-wire slave mode with overflow interrupt.
    USICR = (1<<USIOIE) | (1<<USIWM0) |
            (1<<USICS1) | (0<<USICS0);

    // Init driver status register.
    spiX_status.masterMode       = 0;
}

uint8_t spi_send(uint8_t val)
{
    // 1. Load the data to be sent into the USI Data Register.
    USIDR = val;
    
    // Master should now enable compare match interrupts.
    if( spiX_status.masterMode == 1 ) {
        // 2. Clear the USI Counter Overflow Flag to start the transfer.
        //    This also pre-loads the USI counter.
        USISR = (1<<USIOIF);

        // 3. Manually clock the USI until the transfer is complete.
        //    The USIOIF flag will be set by hardware after 8 clock cycles.
        while((USISR & (1<<USIOIF)) == 0) {
            // Wait for USI counter to be cleared.
            USICR |= (1<<USITC); // Toggle clock output pin.
        }
    }

    return USIDR;
}

void spi_bulk_send( uint8_t *send_buffer, uint8_t count )
{
    while (count--) {
        uint8_t data = *send_buffer++;
        spi_send(data);
    }
}

void spi_bulk_exchange(uint8_t *send_buffer, uint8_t *receive_buffer, uint8_t count)
{
    while ( count-- ) {
        uint8_t data = *send_buffer++;
        // Send data and receive response.
        *receive_buffer++ = spi_send(data);
    }
}

void SPIManager::begin(uint8_t cspin) {
    // pull low for chip select
    GPIO_SET_LOW(A, cspin);
}

void SPIManager::end(uint8_t cspin) {
    GPIO_SET_HIGH(A, cspin);
}

void SPIManager::startMaster() {
    this->_statusRegister = SPI_MODE_MASTER;
    spi_master_init();
}

void SPIManager::startSlave() {
    this->_statusRegister = SPI_MODE_SLAVE;
    spi_slave_init();
}

bool SPIManager::sendCommand(uint8_t& command) {
    command = spi_send(command);
    return true;
}

bool SPIManager::send(uint8_t data) {
    spi_send(data);
    return true;
}

bool SPIManager::sendCommandData(uint8_t size, uint8_t* inoutbuffer) {
    spi_bulk_exchange(inoutbuffer, inoutbuffer, size);
    return true;
}

#endif

/*


*/