CREATE TABLE "birdfeeding" ("id" INTEGER PRIMARY KEY  NOT NULL ,"time" DATETIME NOT NULL ,"event" TEXT NOT NULL );
CREATE TABLE "seedstatus" ("id" INTEGER PRIMARY KEY  NOT NULL ,"time" DATETIME NOT NULL ,"event" TEXT NOT NULL );
