/*  Copyright (c) 2015 B. Sidhipong <bsidhipong@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>. */

#include "SPIManager.h"

#include <avr/common.h>
#include <avr/interrupt.h>
#include <avr/io.h>
#include <util/delay.h>

//#define SLOW_SPI
//#define SOFTWARE_SPI

/*! \brief  Data input register buffer.
 *
 *  Incoming bytes are stored in this byte until the next transfer is complete.
 *  This byte can be used the same way as the SPI data register in the native
 *  SPI module, which means that the byte must be read before the next transfer
 *  completes and overwrites the current value.
 */
uint8_t storedSPIData;

/*! \brief  Driver status bit structure.
 *
 *  This struct contains status flags for the driver.
 *  The flags have the same meaning as the corresponding status flags
 *  for the native SPI module. The flags should not be changed by the user.
 *  The driver takes care of updating the flags when required.
 */
struct SPIdriverStatus_t {
    uint8_t masterMode : 1;        //!< True if in master mode.
    uint8_t transferComplete : 1;  //!< True when transfer completed.
};

volatile struct SPIdriverStatus_t spiX_status;  //!< The driver status bits.

//-----------------------------------------------------------------------
// For MCU with SPI support
#if defined(SPCR)

// set PORT and PIN
#if defined(__AVR_ATmega8535__)
#define PORT_SPI PORTB
#define PIN_SPI PINB
#define DDR_SPI DDRB
#define DD_MOSI DDB5
#define DD_MISO DDB6
#define DD_SCK DDB7
#define DD_CS DDB4
#elif defined(__AVR_ATmega328P__)
#define PORT_SPI PORTB
#define PIN_SPI PINB
#define DDR_SPI DDRB
#define DD_MOSI DDB3
#define DD_MISO DDB4
#define DD_SCK DDB5
#define DD_CS DDB2
#elif defined(__AVR_ATmega1284P__)
#define PORT_SPI PORTB
#define PIN_SPI PINB
#define DDR_SPI DDRB
#define DD_MOSI DDB5
#define DD_MISO DDB6
#define DD_SCK DDB7
#define DD_CS DDB4
#endif

void SPIManager::startSlave() {
    DDR_SPI |= _BV(DD_MISO);                                // output
    DDR_SPI &= ~(_BV(DD_MOSI) | _BV(DD_SCK) | _BV(DD_CS));  // input

    // pull up on ChipSelect
    PORT_SPI |= _BV(DD_CS);

    this->_statusRegister = SPI_MODE_SLAVE;

#ifndef SOFTWARE_SPI
    SPCR = (0 << SPIE) |                // no interrupt
           (1 << SPE) |                 // enable SPI
           (0 << DORD) |                // MSB first
           (0 << MSTR) |                // set as slave
           (0 << CPOL) | (0 << CPHA) |  // mode 0
           (0 << SPR1) | (0 << SPR0);   // CPU freq / 4, no effect in slave mode, clock is generated by master
        
    SPDR = this->_statusRegister;
#endif
}

void SPIManager::startMaster() {
    DDR_SPI &= ~(_BV(DD_MISO));                            // input
    DDR_SPI |= (_BV(DD_MOSI) | _BV(DD_SCK) | _BV(DD_CS));  // output

    // init output
    PORT_SPI &= ~(_BV(DD_MOSI) | _BV(DD_SCK));
    PORT_SPI |= _BV(DD_CS);  // not selected

    this->_statusRegister = SPI_MODE_MASTER;

#ifndef SOFTWARE_SPI
#ifdef SLOW_SPI
    SPCR = (0 << SPIE) |                // no interrupt
           (1 << SPE) |                 // enable SPI
           (0 << DORD) |                // MSB first
           (1 << MSTR) |                // set as master
           (0 << CPOL) | (0 << CPHA) |  // mode 0
           (1 << SPR1) | (1 << SPR0);   // CPU freq / 64
#else
    SPCR = (0 << SPIE) |                // no interrupt
           (1 << SPE) |                 // enable SPI
           (0 << DORD) |                // MSB first
           (1 << MSTR) |                // set as master
           (0 << CPOL) | (0 << CPHA) |  // mode 0
           (0 << SPR1) | (0 << SPR0);   // CPU freq / 64
#endif

    SPSR |= _BV(SPI2X);

    SPDR = this->_statusRegister;
#endif
}

bool SPIManager::receiveCommand(uint8_t& command) {
    if (this->isMaster()) return false;  // not used if master

    bool success = true;

#ifndef SOFTWARE_SPI
    // Wait for reception complete or CS HIGH
    do {
    } while (bit_is_clear(SPSR, SPIF) && bit_is_clear(PIN_SPI, DD_CS));

    // do this before reading SPDR, to not reset SPIF
    if (bit_is_set(PIN_SPI, DD_CS) && bit_is_clear(SPSR, SPIF)) {
        // loop is broken because CS is released (HIGH)
        success = false;
    }

    // copy Data Register
    command = SPDR;
#else


#endif

    return success;
}

bool SPIManager::execCommand(uint8_t size, uint8_t* outbuffer, uint8_t* inbuffer) {
    if (this->isMaster()) return false;  // not used if master

    bool success = true;

#ifndef SOFTWARE_SPI
    for (uint8_t i = 0; i < size; i++) {
        // copy output byte
        SPDR = outbuffer[i];
        // Wait for reception complete or CS HIGH
        do {
        } while (bit_is_clear(SPSR, SPIF) && bit_is_clear(PIN_SPI, DD_CS));

        // do this before reading SPDR, to not reset SPIF
        if (bit_is_set(PIN_SPI, DD_CS) && bit_is_clear(SPSR, SPIF)) {
            // loop is broken because CS is released (HIGH)
            success = false;
            break;
        }

        // copy Data Register
        inbuffer[i] = SPDR;
    }

    SPDR = this->_statusRegister;
#else

#endif

    return success;
}

void SPIManager::begin(uint8_t cspin) {
    // CS low to start transmit
    PORT_SPI &= ~(_BV(DD_CS));
#ifdef SLOW_SPI
    _delay_ms(5);
#endif
}

void SPIManager::end(uint8_t cspin) {
    // CS high to end transmit
    PORT_SPI |= _BV(DD_CS);
}

bool SPIManager::send(uint8_t data) {
    if (this->isSlave()) return false;  // not used if slave

#ifndef SOFTWARE_SPI
    SPDR = data;
    /*
     * The following NOP introduces a small delay that can prevent the wait
     * loop form iterating when running at the maximum speed. This gives
     * about 10% more speed, even if it seems counter-intuitive. At lower
     * speeds it is unnoticed.
     */
    asm volatile("nop");
    // Wait for send complete
    loop_until_bit_is_set(SPSR, SPIF);
#else
    uint8_t v = data;
    for (int b = 0; b < 8; b++) {  // send command
        if ((v & 0x80) != 0) {
            PORT_SPI |= _BV(DD_MOSI);  // high
        } else {
            PORT_SPI &= ~(_BV(DD_MOSI));  // low
        }
        // clock
        PORT_SPI |= _BV(DD_SCK);  // high
        PORT_SPI &= ~(_BV(DD_SCK));  // low
        // next bit
        v <<= 1;
    }

#endif
    return true;
}

bool SPIManager::sendData(uint8_t size, uint8_t* inbuffer) {
    if (this->isSlave()) return false;  // not used if slave

    for (uint8_t i = 0; i < size; i++) {
#ifndef SOFTWARE_SPI
        // copy output byte
        SPDR = inbuffer[i];
        /*
         * The following NOP introduces a small delay that can prevent the wait
         * loop form iterating when running at the maximum speed. This gives
         * about 10% more speed, even if it seems counter-intuitive. At lower
         * speeds it is unnoticed.
         */
        asm volatile("nop");
        // Wait for send complete
        do {
        } while (bit_is_clear(SPSR, SPIF));
#else
        uint8_t v = inbuffer[i];
        for (int b = 0; b < 8; b++) {  // send command
            if ((v & 0x80) != 0) {
                PORT_SPI |= _BV(DD_MOSI);  // high
            } else {
                PORT_SPI &= ~(_BV(DD_MOSI));  // low
            }
            // clock
            PORT_SPI |= _BV(DD_SCK);  // high
            PORT_SPI &= ~(_BV(DD_SCK));  // low
            // next bit
            v <<= 1;
        }
#endif
    }

    return true;
}

bool SPIManager::sendCommand(uint8_t& command) {
    if (this->isSlave()) return false;  // not used if slave

#ifndef SOFTWARE_SPI
    SPDR = command;
    /*
     * The following NOP introduces a small delay that can prevent the wait
     * loop form iterating when running at the maximum speed. This gives
     * about 10% more speed, even if it seems counter-intuitive. At lower
     * speeds it is unnoticed.
     */
    asm volatile("nop");
    // Wait for send complete
    loop_until_bit_is_set(SPSR, SPIF);

    // copy Data Register
    command = SPDR;
#else
    uint8_t v = command;
    for (int b = 0; b < 8; b++) {  // send command
        if ((v & 0x80) != 0) {
            PORT_SPI |= _BV(DD_MOSI);  // high
        } else {
            PORT_SPI &= ~(_BV(DD_MOSI));  // low
        }
        // clock
        PORT_SPI |= _BV(DD_SCK);  // high
        PORT_SPI &= ~(_BV(DD_SCK));  // low
        // next bit
        v <<= 1;
    }
#endif

    return true;
}

bool SPIManager::sendCommandData(uint8_t size, uint8_t* outbuffer, uint8_t* inbuffer) {
    if (this->isSlave()) return false;  // not used if slave

    for (uint8_t i = 0; i < size; i++) {
#ifndef SOFTWARE_SPI
        // copy output byte
        SPDR = outbuffer[i];

        /*
         * The following NOP introduces a small delay that can prevent the wait
         * loop form iterating when running at the maximum speed. This gives
         * about 10% more speed, even if it seems counter-intuitive. At lower
         * speeds it is unnoticed.
         */
        asm volatile("nop");
        // Wait for send complete
        do {
        } while (bit_is_clear(SPSR, SPIF));
        // copy Data Register
        inbuffer[i] = SPDR;
#else
        uint8_t v = outbuffer[i];
        for (int b = 0; b < 8; b++) {  // send command
            if ((v & 0x80) != 0) {
                PORT_SPI |= _BV(DD_MOSI);  // high
            } else {
                PORT_SPI &= ~(_BV(DD_MOSI));  // low
            }
            // clock
            PORT_SPI |= _BV(DD_SCK);  // high
            PORT_SPI &= ~(_BV(DD_SCK));  // low
            // next bit
            v <<= 1;
        }
#endif
    }

    return true;
}

bool SPIManager::sendCommandData(uint8_t size, uint8_t* inoutbuffer) {
    if (this->isSlave()) return false;  // not used if slave

    for (uint8_t i = 0; i < size; i++) {
#ifndef SOFTWARE_SPI
    
        // copy output byte
        SPDR = inoutbuffer[i];

        /*
         * The following NOP introduces a small delay that can prevent the wait
         * loop form iterating when running at the maximum speed. This gives
         * about 10% more speed, even if it seems counter-intuitive. At lower
         * speeds it is unnoticed.
         */
        asm volatile("nop");
        // Wait for send complete
        do {
        } while (bit_is_clear(SPSR, SPIF));
        // copy Data Register
        inoutbuffer[i] = SPDR;
#else
        uint8_t v = inoutbuffer[i];
        for (int b = 0; b < 8; b++) {  // send command
            if ((v & 0x80) != 0) {
                PORT_SPI |= _BV(DD_MOSI);  // high
            } else {
                PORT_SPI &= ~(_BV(DD_MOSI));  // low
            }
            // clock
            PORT_SPI |= _BV(DD_SCK);  // high
            PORT_SPI &= ~(_BV(DD_SCK));  // low
            // next bit
            v <<= 1;
        }
#endif
    }

    return true;
}

void SPIManager::setMosiAsInput() {
#ifndef SOFTWARE_SPI
    SPCR &= ~(_BV(SPE));  // disable hardware SPI
#endif

    DDR_SPI &= ~(_BV(DD_MOSI));   // input
    PORT_SPI &= ~(_BV(DD_MOSI));  // no pullup
}

void SPIManager::setMosiAsOutput() { 
#ifdef SOFTWARE_SPI
    DDR_SPI |= (_BV(DD_MOSI));   // output
    PORT_SPI &= ~(_BV(DD_MOSI));  // low
#else
    startMaster();
#endif
}

void SPIManager::dummyClock() {
    // low to high transition to do one clock cycle
    PORT_SPI |= _BV(DD_SCK);  // high
    PORT_SPI &= ~(_BV(DD_SCK));  // low
}

uint8_t SPIManager::readFromMosi() {
    uint8_t r = 0;
    for (int8_t i = 0; i < 8; i++) {
        r <<= 1;
        r |= (PIN_SPI & (1 << DD_MOSI));
        PORT_SPI |= _BV(DD_SCK);  // high
        
        PORT_SPI &= ~(_BV(DD_SCK));  // low
        
    }

    return r;
}

#endif
